language: java

# Use the 'true' command to avoid up-front dependency fetching, for faster builds
# See http://docs.travis-ci.com/user/languages/java/#Dependency-Management
install: true

script: |
  mvn test \
    --batch-mode \
    --settings .travis-settings.xml \
    -Darquillian.jboss.home=/dev/null \
    -Dgwt.validateOnly \
    -DstaticAnalysis

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  fast_finish: true
